// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZee--2l303L0EBTv6wGbO5mSHjoum6U',
    appId: '1:83896785246:web:9d6bbf7a1d61233a7217cf',
    messagingSenderId: '83896785246',
    projectId: 'ishaqmadlab10',
    authDomain: 'ishaqmadlab10.firebaseapp.com',
    storageBucket: 'ishaqmadlab10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhrT-6CD3I_GSXbvfioRcYsE8cfU2cvRE',
    appId: '1:83896785246:android:031e44e3fb8c555e7217cf',
    messagingSenderId: '83896785246',
    projectId: 'ishaqmadlab10',
    storageBucket: 'ishaqmadlab10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6Xa8gbxHq214GbOj19vI5eLdZtLu40Q',
    appId: '1:83896785246:ios:4185513005664f6f7217cf',
    messagingSenderId: '83896785246',
    projectId: 'ishaqmadlab10',
    storageBucket: 'ishaqmadlab10.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL6Xa8gbxHq214GbOj19vI5eLdZtLu40Q',
    appId: '1:83896785246:ios:4185513005664f6f7217cf',
    messagingSenderId: '83896785246',
    projectId: 'ishaqmadlab10',
    storageBucket: 'ishaqmadlab10.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWZee--2l303L0EBTv6wGbO5mSHjoum6U',
    appId: '1:83896785246:web:b218775e7855eb637217cf',
    messagingSenderId: '83896785246',
    projectId: 'ishaqmadlab10',
    authDomain: 'ishaqmadlab10.firebaseapp.com',
    storageBucket: 'ishaqmadlab10.firebasestorage.app',
  );
}
